bot.token=8449656335:AAG4hMLUkd6EsnIvRDqarQXQ-hZkxiS5JvA
bot.name=@chuk_notification_bot
bot.url=https://osteoid-mui-unblinkingly.ngrok-free.dev

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

server.port=8080

